# Network config
audionet:
  audionet_name: DPT_1d
  audionet_config:
    inp_channels: 2
    out_channels: 2
    encoder_channels: 128
    dim: 64
    num_blocks: [4,6,6,8]
    num_refinement_blocks: 1
    heads: [1,2,4,8]
    ffn_expansion_factor: 2.66
    vpre_channels: 512
    vin_channels: 64
    num_source: 1

videonet:
  videonet_name: ResNetVideoModel
  videonet_config:
    pretrain: /home/xueke/DPT_1d_main/lrw_resnet18_mstcn.pth.tar

# Loss config
loss:
  train:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_snr
    config:
      pit_from: pw_mtx
      threshold_byloss: false
  val:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_sisdr
    config:
      pit_from: pw_mtx
      threshold_byloss: false

# Training config
training:
  system: AudioVisualLightningModule
  gpus: [0,1,2,3]
  parallel: ddp
  epochs: 120
  early_stop:
    monitor: val_loss/dataloader_idx_0
    mode: min
    patience: 10
    verbose: true
  
# Optim config
optimizer:
  optim_name: adamW
  lr: 0.0005
  weight_decay: 0.0001
  betas: [0.9, 0.999]
  
# Sche config
# scheduler: 
#   sche_name: ReduceLROnPlateau
#   sche_config:
#     patience: 10
#     factor: 0.5
scheduler: 
  sche_name: CosineAnnealingLR
  sche_config:
    T_max: 150  # 这是总的迭代周期数，设置成你想训练的总epoch数
# Data config
datamodule:
  data_name: AVSpeechDataModule
  data_config:
    train_dir: /home/xueke/LRS2/mvlrs_v1/raw_data/train/
    valid_dir: /home/xueke/LRS2/mvlrs_v1/raw_data/valid/
    test_dir: /home/xueke/LRS2/mvlrs_v1/raw_data/test/
    n_src: 1
    sample_rate: 16000
    segment: 2.0
    normalize_audio: false
    batch_size: 4
    num_workers: 24
    pin_memory: true
    persistent_workers: false
  
exp:
  exp_name: LRS2-restormer
